### ISSUE TITLE
clone rnv from hartwork rather than dtolpin

### ISSUE THREAD

**Issue by peterstadler** [TEIC/Jenkins#11]
for the original issue see https://github.com/TEIC/TEI/issues/2455

**Comment by hcayless** [comment]
@peterstadler your commit won't work out of the box, as the RNV build process has changed (alas, the documentation has not kept up). See https://github.com/TEIC/teidev-docker/blob/master/Dockerfile#L35-L38 for the steps to build it.

**Comment by peterstadler** [comment]
Thanks @hcayless for the heads up and the pointer!
I now refactored the Dockerfile into a single build because rnv was not working for me otherwise. It failed with 
```#rnv: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by rnv)``` 

Now it's working and shows `rnv version 1.7.11`
